use_frameworks!
ENV["COCOAPODS_DISABLE_STATS"] = "true"


target 'SwiftCamera_Example' do
  pod 'SwiftCamera', :path => '../'

  target 'SwiftCamera_Tests' do
    inherit! :search_paths

    
  end
end
